version: "3"
services:
    prod:
      image: hajh20/microblog:1.0.2-prod
      container_name: "microblog-prod"
      ports:
        - "8000:5000"
      links:
        - dbserver
      environment: 
        DATABASE-URL: mysql+pymysql://microblog:password@dbserver/microblog
    test: 
      image: hajh20/microblog:test
      container_name: "microblog-test"
      volumes: 
        - ".:/home/microblog"
    dbserver: 
      image: mysql/mysql-server:5.7
      hostname: dbserver
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_DATABASE: "microblog"
        MYSQL_USER: "microblog"
        MYSQL_PASSWORD: "password"



# docker run --rm -it -p 8080:80 --name simple-server -v $(pwd)/html/:/var/www/html/ username/imagename:tag

# docker run --name mysql -d -e MYSQL_RANDOM_ROOT_PASSWORD=yes -e MYSQL_DATABASE=microblog -e MYSQL_USER=microblog -e MYSQL_PASSWORD=password mysql/mysql-server:5.7

# docker run --name microblog -d -p 8000:5000 --rm -e SECRET_KEY=my-secret-key --link mysql:dbserver -e DATABASE_URL=mysql+pymysql://microblog:password@dbserver/microblog microblog:1.0.0-prod


# docker run --name microblog-test -v $(pwd):/home/microblog --rm microblog:test


