version: "3"
services:
    prod:
      image: hajh20/microblog:1.0.2-prod
      container_name: "microblog-prod"
      ports:
        - "8000:5000"
      links:
        - dbserver
      environment: 
        DATABASE-URL: mysql+pymysql://microblog:password@dbserver/microblog
    test: 
      image: hajh20/microblog:test
      container_name: "microblog-test"
      volumes: 
        - ".:/home/microblog"
    dbserver: 
      image: mysql/mysql-server:5.7
      hostname: dbserver
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_DATABASE: "microblog"
        MYSQL_USER: "microblog"
        MYSQL_PASSWORD: "password"
