---
-   name: Remove image
    docker_image:
        name: "{{ mysql_image }}"
        state: absent
        force_absent: yes

-   name: Create database container
    docker_container:
        name: mysql
        image: mysql/mysql-server:5.7
        state: started
        pull: yes
        env:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: "microblog"
            MYSQL_USER: "microblog"
            MYSQL_PASSWORD: "password"
        restart_policy: always
        ports:
            - "3306:3306"
