global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["{{ groups['monitoring'][0] }}:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["{{ groups['monitoring'][0] }}:9090"]
  - job_name: "flaskapp"
    static_configs:
      - targets: ["{{ groups['appServer'][0] }}:8000"]
  - job_name: "nginx"
    metrics_path: /prometheus
    static_configs: 
    - targets: ["{{ groups['loadBalancer'][0] }}:9113"]